# Generated by Django 3.1.4 on 2020-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20201216_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='places.Category'),
        ),
    ]
