# Generated by Django 3.1.4 on 2020-12-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201219_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ManyToManyField(blank=True, to='places.Category'),
        ),
    ]
