# Generated by Django 3.1.4 on 2020-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201215_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
